### ISSUE TITLE
iceScrum setup refresh uses wrong URL

### ISSUE THREAD

**Issue by ebonnet31** [icescrum/iceScrum-docker#1]
Hi
I tried to use the icescrum docker image and I have the following problem : 
- Docker for Windows 1.1.2 OK
- Icescrum image OK via Kinematic (beta) 
  - Aug 17, 2016 1:32:52 PM org.apache.catalina.startup.HostConfig deployWAR 
  - INFO: Deployment of web application archive /usr/local/tomcat/webapps/icescrum.war has finished in 85,963 ms 
  - Aug 17, 2016 1:32:52 PM org.apache.coyote.AbstractProtocol start 
  - INFO: Starting ProtocolHandler ["http-nio-8080"] 
  - Aug 17, 2016 1:32:52 PM org.apache.catalina.startup.Catalina start 
  - INFO: Server startup in 86103 ms
- lauching

Then 
Screenshot 1
![icescrum_pb1](https://cloud.githubusercontent.com/assets/3205426/17738533/e0ce6030-6491-11e6-9bec-007979e2039e.png)

Screenshot 2
![icescrum_pb2](https://cloud.githubusercontent.com/assets/3205426/17738538/e7151218-6491-11e6-8685-50b611c84e85.png)

Looks like a URL is redirected and mixed up with docker internal port.

**Comment by noullet** [comment]
Hi,

As explained in the documentation, an important thing about iceScrum is that it needs to know at startup time the external URL that will be used to browse it. By default this URL is http://localhost:8080/icescrum.

It seems that you are using Docker through Docker Machine. In this case, the _Docker Host_ is a VM rather than _localhost_ so it doesn't match the default URL, hence your issue.

Unfortunately, as far as I know a Docker container cannot know the external host and port of its _Docker Host_. Because of this Docker limitation, our Docker image cannot configure automatically the iceScrum URL.

Thus, you have to provide this information manually when starting the container. This is done through Environment variables passed through the _docker run_ command, see https://github.com/icescrum/iceScrum-docker/tree/master/icescrum#environment-variables

You will find an example to start iceScrum here, you can use the "Docker Machine" example: https://github.com/icescrum/iceScrum-docker/tree/master/icescrum#examples. Alternatively, you can configure the environment variables in Kitematic if you prefer using a GUI.

Please note that there is now a more native way to install Docker on Windows and OS X where the _Docker Host_ is _localhost_ so the iceScrum default URL works out of the box. However, it doesn't include Kitematic so you have to use the command line.

You may have to configure the _docker run_ command further, at least by mapping the 8080 container exposed port to an outside port (can be 8080 too), which is required by Docker. It seems that Kitematic does that automatically: in your case the container port has been mapped to port 32771.

To persist the server configuration and data, it is also recommended to mount a volume and configure a DBMS.

**Comment by ebonnet31** [comment]
Hi Nicolas,
I actually tried that (ICESCRUM_HOST + ICESCRUM_PORT in kinematic) but for some reason : the external port # always increase or changes when I specify ICESCRUM_PORT in Kinematic.
For some reason, specifying the ICESCRUM_PORT changes the default port externally allocated to icescrum. see screenshots.

![icescrum_pb4](https://cloud.githubusercontent.com/assets/3205426/17779758/1bbfdb38-6569-11e6-96a5-02e56db5e87b.png)
![icescrum_pb3](https://cloud.githubusercontent.com/assets/3205426/17779759/1bc04d16-6569-11e6-9b99-e8de0ac5ec50.png)

**Comment by noullet** [comment]
Hi Emmanuel,

The Docker "run" command requires explicit port mapping to run an image with exposed ports. This is not related to iceScrum, every app that wants to export a port faces this issue.

Kitematic does some magic on top of Docker Run to give the impression that it works out of the box. Unfortunately the magic falls short: the port mapping decided by Kitematic changes while you don't want it to and again this is not related to iceScrum.

I see that there is a "Ports" tab in the Kitematic config, you can probably enforce the port mapping here, see http://stackoverflow.com/questions/29977667/why-did-the-ip-and-port-number-change-in-kitematic. You want to map the internal port 8080 to the same external port as ICESCRUM_PORT.

**Comment by ebonnet31** [comment]
Setting the port mapping in Kinematic container settings made it !
Thanks
